### ISSUE TITLE
size text does not look good or familiar 

### ISSUE THREAD

**Issue by pathnirvana** [pnfo/file-server#20]
I have updated the website https://tipitaka.lk/cloud/ with your changes however the rendering of sizes look bit off.
You can compare it with the old version at https://tipitaka.lk/library/
I would like to hear your suggestions for improvement. English names would look familiar IMO 
<img width="541" alt="Screenshot 2023-03-20 at 8 04 27 PM" src="https://user-images.githubusercontent.com/18088975/226347139-19a419ed-bc38-4969-91f1-1d22707f5950.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/18088975/226347374-36fd444b-18f9-48f3-b36b-9d5064945811.png">

**Comment by dinithija** [comment]
දිග වැඩි වන නිසා සමාන්‍යයෙන් ඒකක තනි පේළියක දෙයාකාරයෙන්ම ලියා තබන්නේ නැහැ සහ මා කලින් පැවසූ පරිදි පැත්ත ද මාරු විය යුතුයි. ඔබ පටලැවෙනවා යැයි උපකල්පනය කළාට බොහෝ අයට KB, TB, PB, EB, ZB, YB, BB ආදියෙහි වචනය කුමක්දැයි මතක් කර ගැනීමට හැකි වන්නේ එහි මුල අල්ලා ගැනීමට උදව් වන සිංහල අකුරින් තිබෙන විටයි. 

කි.ග්‍රෑ. 5 -- 5 KG
මි.ලී 750 -- 750 ml
සෙ.මී. 25 -- 25 cm
ගි.බ. 60 -- 60 GB

ඉඩ ඇහිරෙන නිසා දැනට මෙය කලින් පැවති ආකාරයෙන් තබන්නම්. පසු කාලයක එවැනි ගැටළුවක් නැතැයි ඔබට හැඟී ගියහොත් වෙනස් කරගන්න හෝ ඕනෑම විටෙක අපගේ සමූහය ඇමතීමට හැකියි.

**Comment by dinithija** [comment]
@pathnirvana මෙය කලින් පැවසීමට අමතක වුනා. `පරිගණක සඳහා` වන සබැඳියේ https://tipitaka.lk/library/download/448 ඊට අදාළ ගොනු(ව) නැහැ. මාගේ අත්වැරදීමක් නොවෙයි.

![image](https://user-images.githubusercontent.com/80757159/226670661-3f704ff1-f333-4822-a12f-a277d6245606.png)

**Comment by pathnirvana** [comment]
sorry the link should be like https://tipitaka.lk/library/448/download 

download comes after the id
